### ISSUE TITLE
能分享一下生活模板架构吗？

### ISSUE THREAD

**Issue by yunwenlong** [Light413/dctt#4]
我想做一个类似于这样的生活服务平台，不知道都涉及到哪些模块。方便分享一下吗？

**Comment by Light413** [comment]
我不太理解你说的架构指哪方面的；

如果整体作为一个平台的话，应有手机端APP、网站主页、后台接口服务，后台管理。此时你应该整体思考要做成什么样，如何去设计、实现，运营等。如果你不是各方面都熟悉的话，这个实际做起来估计要深入学习下。

如果单独作为一个APP来说，一般根据业务来驱动，就是你的APP定位为的问题了，你要实现什么功能、有什么页面等。目前来说我这个项目这方面也是在摸索，我有时也迷惑我究竟要做什么功能？其实这也算是产品设计的问题了。如果能找到定位，目标用户，做起来应该也很明确。

如果具体到APP本身开发技术而言，如前所述也是根据你要什么来驱动的。知道了你想要什么，你才清楚下一步如何该如何走。

再来说我这个项目，包含安卓、苹果、网站主页，后台服务器;
安卓：我的H5开发的，因为我对原生Android不熟悉，h5跨平台也可以导出苹果的。

苹果：此项目，原生开发，因为我本身对此很熟悉。

后台接口：php开发，没什么框架库之类的，就是手写PHP文件接口来实现数据库的操作。

后台管理：目前我还没来及做，以后有时间我会跟上。

总之目前还是不成熟阶段，我也在不断的摸索完善。

**Comment by yunwenlong** [comment]
感谢您的回复！
    可能我表达的不够清楚，因为我也是刚研究生活服务平台这一块儿，所涉及到的功能方面会比较迷茫，我目前的打算是针对用户和商家两端，用户端就是H5和小程序，这两个大差不差，因为我并没有深入去做调研，也并不是产品、业务出身，涉及到的功能方面我比较迷茫，不知道到底要做一些什么东西。想请教一下，你在做的时候，会涉及到哪些功能呢？这个产品所涉及到的哪些业务呢？
目前我所设想的项目是：微信公众号+小程序，网站主页，后台管理
使用到的技术是：
    服务端：java(springboot)
    前端：vue
    数据库：mysql
    缓存：redis

**Comment by Light413** [comment]
> 感谢您的回复！
> 可能我表达的不够清楚，因为我也是刚研究生活服务平台这一块儿，所涉及到的功能方面会比较迷茫，我目前的打算是针对用户和商家两端，用户端就是H5和小程序，这两个大差不差，因为我并没有深入去做调研，也并不是产品、业务出身，涉及到的功能方面我比较迷茫，不知道到底要做一些什么东西。想请教一下，你在做的时候，会涉及到哪些功能呢？这个产品所涉及到的哪些业务呢？
> 目前我所设想的项目是：微信公众号+小程序，网站主页，后台管理
> 使用到的技术是：
> 服务端：java(springboot)
> 前端：vue
> 数据库：mysql
> 缓存：redis



> 感谢您的回复！
> 可能我表达的不够清楚，因为我也是刚研究生活服务平台这一块儿，所涉及到的功能方面会比较迷茫，我目前的打算是针对用户和商家两端，用户端就是H5和小程序，这两个大差不差，因为我并没有深入去做调研，也并不是产品、业务出身，涉及到的功能方面我比较迷茫，不知道到底要做一些什么东西。想请教一下，你在做的时候，会涉及到哪些功能呢？这个产品所涉及到的哪些业务呢？
> 目前我所设想的项目是：微信公众号+小程序，网站主页，后台管理
> 使用到的技术是：
> 服务端：java(springboot)
> 前端：vue
> 数据库：mysql
> 缓存：redis

技术路线没问题，那主要就是功能定位问题了。

有用户和商家，那你这是商品买卖业务了。

商家端：基本涉及到上传、发布、删除、管理商品，也会涉及到支付问题。可以是手机端或pc操作。
用户：浏览商品列表、详情，收藏，支付、分享等，这个可参考一些购物的APP都差不多。
